### ISSUE TITLE
bassmaster

### ISSUE THREAD

**Issue by F4l13n5n0w** [timip/OSWE#1]
Hi,

Wondering have you successful setup the bassmater?

i keep got the following error, when using command `npm install bassmaster@1.5.1`:

```
    internals.http.plugin().require('../', function (err) {
                   ^

TypeError: internals.http.plugin is not a function
    at Object.internals.main (/home/osboxes/bassmaster/examples/batch.js:74:20)
    at Object.<anonymous> (/home/osboxes/bassmaster/examples/batch.js:88:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by nofacenonamedude** [comment]
Were you able to deploy the atmail server? hints?

I'll post an update when I get to the bassmaster

**Comment by timip** [comment]
@F4l13n5n0w I guess you got this error when you try to run bassmaster (not during installation). Take a look on example/batch.js on newer version of bassmaster and figure out how to make it works. 
@nofacenonamedude If you are in OSWE lab, you should able to find a way to setup Atmail on your own machine.

**Comment by nofacenonamedude** [comment]
@timip I'm not currently using the lab - kinda exploring things on my own before the big bang :) !

**Comment by F4l13n5n0w** [comment]
@n_hashtag @timip, i was using Ubuntu Server 16.04, nodejs v8 and i figured
out my error was due to a wrong version of hapi module, i changed it to
hapi@12 with the latest example/batch.js and it now working perfectly.


Thanks,

F4l13n5n0w

**Comment by timip** [comment]
Nice!
